### PR TITLE
Refactored for better readability

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by joesanford** [comment]
What style guide is this adhering to? It was already put through PEP8.

**Comment by ghost** [comment]
I just wanted to make it more readable.

**Comment by joesanford** [comment]
IMO you reduced it. _shrug_

**Comment by ghost** [comment]
Oh, well I am Python beginner. Now I follow PEP8 style.

**Comment by remggo** [comment]
You can check your Code with the following Package [PEP8](https://pypi.python.org/pypi/pep8)

**Comment by ghost** [comment]
Okay thanx

**Comment by joesanford** [comment]
"Oh, well I am Python beginner. Now I follow PEP8 style."

Then I don't understand why you wiped my time I took to PEP8 a script out with a "readability" PR. Had some things to add but I am going to go contribute more elsewhere now.

**Pull request merged**
