### PR TITLE
Do not download files that already exists

### PR DESCRIPTION
**Pull request by dolohow**
As this program fetches wallpapers daily, there is no reason to do that
when the program is invoked twice the same day.

By verifying whether the wallpaper file already exists we can conclude
that the program was already run during that day.

### CODE REVIEW

**Comment by ssimunic** [comment]
User can still specify to run the program every hour and this wouldn't allow then the wallpaper to be changed, however, there is some tweaking that needs to be done.

**Comment by dolohow** [comment]
So maybe we could store the information in ~/.cache when we fetched last time along with pictures?

**Comment by remggo** [comment]
Maybe store the URLs of the last fetched images (e.g. 3 URLs should be enough)

**Comment by dolohow** [comment]
And where you want to put that file? I could use a shelve module for that.

**Comment by ssimunic** [comment]
Instead of saving picture as subreddit name + date, we could add hour into date so it doesn't override existing one, if 'hourly' option is used.

**Comment by dolohow** [comment]
Could it happen that for example at 1am and 2am the wallpaper could be the same?

**Comment by ssimunic** [comment]
@dolohow , yeah, wallpaper on the subreddit could be the same. Then another option is to save reddit post ID in filename and if it is same, just don't download it

**Comment by dolohow** [comment]
I would go with that option and let's forget about the date, we already have ctime, let's say wallpaper-ID.jpg.  What do you guys think?

**Comment by remggo** [comment]
subreddit-ID.jpg would do the Trick

**Comment by ssimunic** [comment]
@dolohow @remggo Good suggestion. We should go with this one.

**Comment by dolohow** [comment]
I will try to prepare appropriate PR for that.

**Comment by dolohow** [comment]
@ssimunic Please review this new approach.

Thanks

**Comment by ssimunic** [comment]
@dolohow Good job!

**Pull request merged**
